FROM debian:7

RUN apt-get update
RUN apt-get install -y freetds-common freetds-bin unixodbc apache2 \
    php5-sybase php5 libapache2-mod-php5
RUN apt-get install -y nano curl


#RUN mkdir /var/www
WORKDIR /var/www
RUN chown www-data:www-data /var/www

RUN rm /var/www/index.html

COPY application ./applications
COPY system ./system

#COPY index.php .

CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]